name: Use Actions Deploy Hexo To Github

on:
  push:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install hexo
        run: sudo npm install hexo-cli -g

      - name: Generate
        env:
          SOURCE_CODE: https://github.com/axpv-code/the-new-minenakjffkafewfwe
          THEME_WAREHOUSE: https://github.com/axpv-code/hexo-theme-nexmoe
        run: |
          git clone -b master $SOURCE_CODE gh
          cd gh
          npm install
          rm -rf .github
          rm -rf .gitignore
          git clone $THEME_WAREHOUSE themes/themes
          npm i --save hexo-wordcount
          hexo generate
          cd public
          curl lncn.org > vpn.html
          mkdir cdn-cgi/bm/cv/
          cd cdn-cgi/bm/cv/
          wget lncn.org/cdn-cgi/bm/cv/
          cd ../../../
          echo "4c.ddns.mobi" > CNAME
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./gh/public
          publish_branch: hexo
          personal_token: ${{ secrets.TOKEN }}
