name: Use Actions Deploy Hexo To Github

on:
  push:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install hexo
        run: sudo npm install hexo-cli -g

      - name: Generate
        env:
          SOURCE_CODE: https://github.com/axpv-code/the-new-minenakjffkafewfwe
          THEME_WAREHOUSE: https://github.com/axpv-code/hexo-theme-nexmoe
        run: |
          git clone -b master $SOURCE_CODE gh
          cd gh
          npm install
          rm -rf .github
          rm -rf .gitignore
          git clone $THEME_WAREHOUSE themes/themes
          npm i --save hexo-wordcount
          hexo generate
          cd public
          wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-i686.tar.bz2
          tar -jxvf phantomjs-1.9.8-linux-i686.tar.bz2
          sudo cp phantomjs-1.9.8-linux-i686/bin/phantomjs /bin/phantomjs
          echo "/*
           * desc: get snapshot from url
           * example: phantomjs snap.js http://www.baidu.com baidu.png
           */
          
          var page = require('webpage').create();
          var args = require('system').args;
          
          var pageW = 1024;
          var pageH = 768;
          
          page.viewportSize = {
            width: pageW,
            height: pageH
          };
          
          var url =  args[1];
          var filename = args[2];
          page.open(url, function (status) {
              if (status !== 'success') {
                  console.log('Unable to load ' + url + ' !');
                  phantom.exit();
              } else {
                  window.setTimeout(function () {
                      page.clipRect = { left: 0, top: 0, width: pageW, height: pageH };
                      page.render(filename);
                      console.log('finish:', filename);
                      phantom.exit();
                  }, 1000);
              }
          });" > snap.js
          phantomjs snap.js youtube.com ytb.png
          echo "4c.ddns.mobi" > CNAME
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./gh/public
          publish_branch: hexo
          personal_token: ${{ secrets.TOKEN }}
